
-- Usuwanie istniejących tabel, jeśli istnieją
DROP TABLE OrderDetails CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Products CASCADE CONSTRAINTS;
DROP TABLE Customers CASCADE CONSTRAINTS;

-- Tworzenie tabeli klientów
CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    RegistrationDate DATE NOT NULL,
    Country VARCHAR2(50) NOT NULL
);

-- Tworzenie tabeli produktów
CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductName VARCHAR2(100) NOT NULL,
    Category VARCHAR2(50) NOT NULL,
    Price NUMBER(10, 2) NOT NULL,
    Stock NUMBER NOT NULL
);

-- Tworzenie tabeli zamówień
CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    OrderDate DATE NOT NULL,
    TotalAmount NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_customer FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- Tworzenie tabeli szczegółów zamówień
CREATE TABLE OrderDetails (
    OrderDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    PricePerUnit NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    CONSTRAINT fk_product FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

-- Wstawianie przykładowych danych do tabeli klientów
INSERT INTO Customers (Name, Email, RegistrationDate, Country)
VALUES ('John Doe', 'john.doe@example.com', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'USA');

INSERT INTO Customers (Name, Email, RegistrationDate, Country)
VALUES ('Jane Smith', 'jane.smith@example.com', TO_DATE('2022-11-10', 'YYYY-MM-DD'), 'Canada');

INSERT INTO Customers (Name, Email, RegistrationDate, Country)
VALUES ('Alice Johnson', 'alice.johnson@example.com', TO_DATE('2023-05-22', 'YYYY-MM-DD'), 'UK');

-- Wstawianie przykładowych danych do tabeli produktów
INSERT INTO Products (ProductName, Category, Price, Stock)
VALUES ('Smartphone', 'Electronics', 699.99, 50);

INSERT INTO Products (ProductName, Category, Price, Stock)
VALUES ('Laptop', 'Electronics', 1199.99, 30);

INSERT INTO Products (ProductName, Category, Price, Stock)
VALUES ('Desk Chair', 'Furniture', 150.00, 20);

-- Wstawianie przykładowych danych do tabeli zamówień
INSERT INTO Orders (CustomerID, OrderDate, TotalAmount)
VALUES (1, TO_DATE('2023-06-10', 'YYYY-MM-DD'), 849.99);

INSERT INTO Orders (CustomerID, OrderDate, TotalAmount)
VALUES (2, TO_DATE('2023-06-12', 'YYYY-MM-DD'), 1199.99);

-- Dodanie większej ilości zamówień
INSERT INTO Orders (CustomerID, OrderDate, TotalAmount)
VALUES (1, TO_DATE('2023-07-15', 'YYYY-MM-DD'), 399.99);

INSERT INTO Orders (CustomerID, OrderDate, TotalAmount)
VALUES (3, TO_DATE('2023-08-05', 'YYYY-MM-DD'), 799.99);

INSERT INTO Orders (CustomerID, OrderDate, TotalAmount)
VALUES (2, TO_DATE('2023-09-20', 'YYYY-MM-DD'), 549.99);

INSERT INTO Orders (CustomerID, OrderDate, TotalAmount)
VALUES (3, TO_DATE('2023-10-10', 'YYYY-MM-DD'), 950.00);

-- Wstawianie przykładowych danych do tabeli szczegółów zamówień
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, PricePerUnit)
VALUES (1, 1, 1, 699.99);

INSERT INTO OrderDetails (OrderID, ProductID, Quantity, PricePerUnit)
VALUES (1, 3, 1, 150.00);

INSERT INTO OrderDetails (OrderID, ProductID, Quantity, PricePerUnit)
VALUES (2, 2, 1, 1199.99);

-- Dodanie szczegółów do nowych zamówień
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, PricePerUnit)
VALUES (3, 3, 2, 150.00);

INSERT INTO OrderDetails (OrderID, ProductID, Quantity, PricePerUnit)
VALUES (4, 1, 1, 699.99);

INSERT INTO OrderDetails (OrderID, ProductID, Quantity, PricePerUnit)
VALUES (5, 2, 1, 1199.99);

INSERT INTO OrderDetails (OrderID, ProductID, Quantity, PricePerUnit)
VALUES (6, 3, 1, 150.00);

-- Wyświetlanie danych (opcjonalne)
SELECT * FROM Customers;
SELECT * FROM Products;
SELECT * FROM Orders;
SELECT * FROM OrderDetails;

-- Łączenie tabel dla analizy
SELECT c.Name AS CustomerName, o.OrderDate, p.ProductName, od.Quantity, od.PricePerUnit
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID;
